In [46]:
import numpy as np

In [47]:
l1 = [[1,2,3],[4,5,6]]

a = np.array([1,2,3,4,5,6])

# CTRL+Space
ra = a.reshape(2,3)

In [48]:
a.reshape?

Docstring:
a.reshape(shape, order='C')

Returns an array containing the same data with a new shape.

Refer to `numpy.reshape` for full documentation.

See Also
--------
numpy.reshape : equivalent function

Notes
-----
Unlike the free function `numpy.reshape`, this method on `ndarray` allows
the elements of the shape parameter to be passed in as separate arguments.
For example, ``a.reshape(10, 11)`` is equivalent to
``a.reshape((10, 11))``.
Type:      builtin_function_or_method


In [49]:
# TODO: why did not reshaped?
a.shape
a.ndim

1

In [50]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
a[2,-2:]

array([8, 9])

In [54]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])